Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 6
   using_raw_point: 1
   point_step: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 1280
   image_height: 720
   camera_intrinsic:
      [522.0546264648438, 0.0, 641.3374633789062,
      0.0, 522.0546264648438 , 357.7483825683594,
      0.0, 0.0, 1.0] 
   camera_dist_coeffs: [0,0, 0,0,0]  #k1, k2, p1, p2, k3

   # Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R:
         [0.0272327, -0.999623, 0.0035982,
            -0.0338817,  -0.0045205, -0.999416,
            0.999055,  0.0270949,  -0.033992]
   camera_ext_t: [0.050166, 0.0474116, -0.0312415] 
  # camera_ext_t: [0,0,0] 
   #camera_ext_R:
  #       [0.0272327, -0.999623, 0.0035982,
  #        -0.0338817,  -0.0045205, -0.999416,
   #       0.999055,  0.0270949,  -0.033992]
   #camera_ext_t: [0.0504873, 0.060587, -0.0541128] 
  # camera_ext_t: [0,0,0] 
   # Rough extrinsic value, form CAD model, is not correct enough, but can be online calibrated in our datasets.
   # camera_ext_R:
   #    [0, 0, 1,
   #     -1, 0, 0,
   #     0, -1, 0]
   # camera_ext_t: [0,0,0] 
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30